### ISSUE TITLE
OOM when run benchmark

### ISSUE THREAD

**Issue by lengthmin** [Daninet/hash-wasm#14]
benchmark code: https://gist.github.com/lengthmin/86c4cf3b02d4280aafad71e0f1b04376

when I run the above benchmark, it raise error OOM:
![image](https://user-images.githubusercontent.com/13938334/115228579-89ff7380-a144-11eb-8d6a-b0ab90eb1a5f.png)

and I just use `while(1) md5(_10k);` it raise OOM as well
![image](https://user-images.githubusercontent.com/13938334/115228426-56244e00-a144-11eb-8d5e-c7aa9d0eff6e.png)

**Comment by lengthmin** [comment]
in MacOS 11

both node 12/14 and blake3/md5 will raise OOM Error

maybe have memory leak

**Comment by Daninet** [comment]
I traced it back to a memory leak in Node.js's Buffer.from() function: https://github.com/nodejs/node/issues/38300

**Comment by lengthmin** [comment]
One more point

I write some wasm example by using Rust: https://github.com/lengthmin/node-hash-benchmark

has not meeted OOM problem

**Comment by lengthmin** [comment]
and the error raised in node 12.. so maybe not `Buffer.from` problem

**Comment by Daninet** [comment]
There is an issue with your benchmark code. The md5() function returns a promise and you don't have an await there. If you want to make sync benchmarks then you can use the createMD5() function to get a sync interface.
In node v12.22.1 I don't get memory leaks when I use `await md5()` or `createMD5()`

**Comment by lengthmin** [comment]
how to use createMD5() as a sync operation?
can you give me a example?


still oom
```js
libs.forEach(([name, lib]) => {
  sizes.forEach(([sizeName, content]) => {
    suite.add(`${name}#${sizeName}`, () => {
      createMD5().then((v) => {
        v.init();
        v.update(contents);
        return v.digest();
      });
    });
  });
});
``

**Comment by Daninet** [comment]
createMD5() is doing async compilation and initialization of the WASM binary and it should go outside of the loop.

```
// before benchmark
const hasher = await createMD5();

// in benchmark loop
hasher.init();
hasher.update(data);
hasher.digest();
```

**Comment by lengthmin** [comment]
well, that works

`createMD5` is a promise..

```js
const { createMD5 } = require('hash-wasm');
console.log('start', process.memoryUsage());
for (let i = 0; i < 1e6; i++) {
  createMD5();

  if (i % 1e3 === 0) {
    gc();
    console.log('step', i, 'rss', process.memoryUsage().rss);
  }
}
gc();
console.log('end', process.memoryUsage());
```

```
start {
  rss: 20869120,
  heapTotal: 5132288,
  heapUsed: 2946944,
  external: 1005669,
  arrayBuffers: 232088
}
step 0 rss 22200320
step 1000 rss 32305152
step 2000 rss 42303488
step 3000 rss 52396032
step 4000 rss 53264384
step 5000 rss 59506688
step 6000 rss 64008192
step 7000 rss 70402048
step 8000 rss 77012992
step 9000 rss 84070400
step 10000 rss 90566656
step 11000 rss 97431552
step 12000 rss 104558592
step 13000 rss 111386624
step 14000 rss 118321152
step 15000 rss 125153280
step 16000 rss 131887104
step 17000 rss 139706368
step 18000 rss 146907136
step 19000 rss 154718208
step 20000 rss 161570816
step 21000 rss 168488960
step 22000 rss 175427584
step 23000 rss 182239232
step 24000 rss 189063168
```

so is this a memory leak?

**Comment by Daninet** [comment]
Creating thousands of new promises synchronously without giving them a chance to resolve is not something you would normally do.
I don't understand why did you put the createMD5() inside the loop.

```
const { createMD5 } = require('hash-wasm');
const str = 'x'.repeat(1000);

console.log('start', process.memoryUsage());

createMD5().then(hasher => {
  for (let i = 0; i < 1e6; i++) {
    hasher.init();
    hasher.update(str);
    hasher.digest();
    if (i % 1e5 === 0) {
      gc();
      console.log('step', i, 'rss', process.memoryUsage().rss);
    }
  }
  gc();
  console.log('end', process.memoryUsage());
});
```

**Comment by lengthmin** [comment]
actually, I know I should not put it in loop, and I just want to know is it a promise-related problem.

Thanks for your help!
