### ISSUE TITLE
Feature Request: crc32c (Castagnoli)

### ISSUE THREAD

**Issue by TyrisDavidLopez** [Daninet/hash-wasm#20]
It would be nice if we could get the crc32c using Castagnoli algorithm

thank you for your great work

**Comment by tonybolanyo** [comment]
Hi!
It would be nice to have this. It's used in Google Storage by default

**Comment by Daninet** [comment]
Has landed in [v4.9.0](https://github.com/Daninet/hash-wasm/releases/tag/v4.9.0)!

**Comment by tonybolanyo** [comment]
Only nine hours after my comment. You're lightning fast!!!!

**Comment by Daninet** [comment]
It wasn't a hard thing to do, because CRC32C differs only in one constant from CRC32. 😅
