### ISSUE TITLE
Please release Deno versions

### ISSUE THREAD

**Issue by yuhr** [Daninet/hash-wasm#30]
https://deno.land/x/hashwasm@v4.1.0-deno2

The Deno version of this package is still 4.1.0. Could you release it along with the timing of npm releases?

**Comment by Daninet** [comment]
Yeah, I need to repair the build script which I had for Deno.

Until then you can import the latest version using ESM CDNs like Skypack.

```js
import { md5 } from "https://cdn.skypack.dev/hash-wasm@4";
```
OR
```js
import { md5 } from "https://esm.run/hash-wasm@4";
```

**Comment by Daninet** [comment]
Now it should be possible to import it directly: `import {md5} from "npm:hash-wasm";`
