### ISSUE TITLE
Browser-only implementation

### ISSUE THREAD

**Issue by SlashScreen** [Daninet/hash-wasm#34]
I'm trying to use bcrypt in vanilla js client-side for password stuff, and so I was trying to use the bcrypt dist to keep things speedy and tidy. However, no matter what I try, the javascript won't find bcrypt in the minified file. It just keeps telling me that it cannot find bcrypt in the file. 
here is my code:
```
import { bcrypt } from "./vendor/bcrypt.umd.min.js"
var process;

import "./vendor/jquery.js";

$('#signup').on("submit", function(event) {
    return process();
});

process = async function() {
    var key, salt;
    console.log("begin hash");
    salt = new Uint8Array(16);;
    window.crypto.getRandomValues(salt);
    key = (await bcrypt({
        password: "pass",
        salt,
        costFactor: 10,
        outputType: "encoded"
    }));
    return console.log(key);
}; 
```

I have tried both the import and the <script> way. Is my smooth brain missing something? I un-minified the bcrypt.umd.min.js to take a closer look at it, and it looks like maybe the B function might be what I need to call instead? Although really, I have no idea.
If you could help me out I would be most grateful. And, I would like to keep it to just the bcrypt distro, since that's the only algorithm I'm using. Thanks!

**Comment by SlashScreen** [comment]
Should add that if the syntax is a bit strange, it's because I wrote this using coffeescript.

**Comment by Daninet** [comment]
Hey. I'm not familiar with the coffeescript toolchain, but it works with Webpack if I load it like this:
https://codesandbox.io/s/angry-dirac-tpbwb?file=/src/App.js

Did you try just importing it without a variable?
`import "./vendor/bcrypt.umd.min.js";`
In this way it should create a global variable called `hashwasm`:
```
key = (await hashwasm.bcrypt({...}));
```
