### ISSUE TITLE
Synchronous API

### ISSUE THREAD

**Issue by paulmelnikow** [Daninet/hash-wasm#35]
Hi! I noticed at https://github.com/Daninet/hash-wasm/blob/master/CHANGELOG.md#401-august-29-2020 that briefly this library offered a synchronous API, but it was removed since Chrome disallows WebAssembly binaries larger than 4 kb.

In my use case, the hashes need to be computed synchronously. However, I see a couple possible solutions:

1. Initialize the WASM object asynchronously, and then use it to compute synchronous hashes.
2. Use one of the hash functions which is under 4k, like CRC 32.

Would you consider offering a hybrid async / sync API to support this use case?

**Comment by Daninet** [comment]
Hey! Most algorithms don't fit into the 4k limit, and I think it's more important to have a consistent API.
So the first option (await createCRC32() + init().update().digest() is the preferred way for sync usage.

**Comment by paulmelnikow** [comment]
Ah, got it! I didn't realize that was possible. Thanks!

**Comment by angelobernila** [comment]
Hello guys. Wonder how to make it a sync function, I need it to run in a for loop.
