### ISSUE TITLE
Update README benchmarks to mention noble-hashes

### ISSUE THREAD

**Issue by paulmillr** [Daninet/hash-wasm#36]
This needs to be done after https://github.com/Daninet/hash-wasm-benchmark/pull/8 is merged and deployed

I think it's great to have noble there because it's the fastest JS implementation for many hash functions. I could do a PR, but i'm using M1 Mac, which is fast, maybe you wanted to do it on your machine.

**Comment by paulmillr** [comment]
@Daninet cc

**Comment by Daninet** [comment]
Added it.
