### ISSUE TITLE
After opening the console, the md5 calculation speed is greatly reduced

### ISSUE THREAD

**Issue by kevinzhao2233** [Daninet/hash-wasm#38]
I use the [Demo](https://stackoverflow.com/questions/768268/how-to-calculate-md5-hash-of-a-file-using-javascript/63287199#63287199) provided in Readme.md for testing. If the page has not opened the console, the calculation speed is very objective, but once the console is opened, the calculation speed will be reduced by about 3 times.

You can [open this example](https://codesandbox.io/s/hash-wasm-md5-66n6mi?file=/index.html) for testing.

Below is a screenshot of my test.

Don't open console ☟
![image](https://user-images.githubusercontent.com/42138464/165007533-4f1b98bc-c3c8-4e1e-ad3a-da11ed1a76a6.png)

Open the console ☟
![image](https://user-images.githubusercontent.com/42138464/165007628-1a06fe72-a71a-47fa-8b61-afedc773c20c.png)

**Comment by Daninet** [comment]
Yeah this is a known issue. Chrome disables certain JS/WASM optimizations when the Dev Tools is open. It doesn't happen with Firefox. I also added some time ago a warning message to the benchmark page about it here: https://daninet.github.io/hash-wasm-benchmark/
I'm not sure what else could I do here. 🤔

**Comment by kevinzhao2233** [comment]
It turns out that this is the case, it can only hope that chrome can optimize it.
