### ISSUE TITLE
Password hashing using argon2id

### ISSUE THREAD

**Issue by sudarshansb143** [Daninet/hash-wasm#40]
I am `hash-wasm` with `angular 12` in order to hash password on FE.  My current implementation is 

```js 
let hashedPassword  = await argon2id({
      password: dummy,
      salt: dummy,
      parallelism: 4,
      iterations: 1,
      memorySize: 2097152, // use 2097152KB memory
      hashLength: 128, // output size = 128 bytes
    });

```

But with this implementation I am having 
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/43947282/172824706-94ca2dbc-d81a-4fe0-a221-a6cbc827822b.png">

But, if I change `memorySize` to `32768` it works fine. 

So, does `argon2id` have any max limit for memorySize ?

Sidenote:
If we have any other alternative which works with angular without any build time issues then that would be also helpful

**Comment by Daninet** [comment]
This is a known limitation of JS engines... You only allow allocating maximum 2GB of RAM for the WASM instance and you hit this limit.
There [are movements](https://v8.dev/blog/4gb-wasm-memory#:~:text=Thanks%20to%20recent%20work%20in,512MB%20or%201GB%20of%20memory!) to increase this limit, but it would require recompiling the code, which would break compatibility with other browsers.

**Comment by sudarshansb143** [comment]
After doing some trial and error I am able to hash the passwords with 
```
memorySize: 2097121
```

But, once I increased this number (either by 1 or n) it is breaking.
