### ISSUE TITLE
React-Native Support (Android and iOS)

### ISSUE THREAD

**Issue by Balanced02** [Daninet/hash-wasm#41]
I tried using the `argon2id` encryption function on React-native `v0.70.5` and got an error

### Error:
Module must be either an ArrayBuffer or an Uint8Array (BufferSource), object given

I already have crypto and other required libraries setup already. 

I have a dummy project setup on this [repository](https://github.com/Balanced02/BufferIssue)

**Comment by Daninet** [comment]
Is the error happening within hash-wasm? I need more details.

**Comment by Daninet** [comment]
I don't have time to debug your code, so I'm closing this issue due to missing details.
