### ISSUE TITLE
sha1: all chunk file time >  total file time

### ISSUE THREAD

**Issue by CBulFel** [Daninet/hash-wasm#5]
sha1 It takes longer to calculate all the fragments of the file than to calculate the total time for the entire file.

`

```
import { createSHA1 } from 'hash-wasm'

const chunkSize = 10 * 1024 * 1024
let wasmSha1 = null
const fileReader = new FileReader()

function getChunkCount(totalSize) {
	return Math.floor(totalSize / chunkSize)
}

function handleChunkSha1(chunk) {
	return new Promise((resolve, reject) => {
		fileReader.onload = async (e) => {
				if (!wasmSha1) {
					wasmSha1 = await createSHA1()
					wasmSha1.init()
				}
				const view = new Uint8Array(e.target.result)
				wasmSha1.update(view)
				resolve()
		}

		fileReader.readAsArrayBuffer(chunk)
	})
}

const readVideoFile = async (file) => {
	const maxCount = getChunkCount(file.size)

	for (let i = 0; i <= maxCount; i++) {
		const chunk = file.slice(chunkSize * 1, Math.max(chunkSize * (i + 1), file.size))
		await handleChunkSha1(chunk)
	}

	const hash = wasmSha1.digest()
	return Promise.resolve(hash)
}

readVideoFile(file)
```

 this file is over 1G
`

**Comment by Daninet** [comment]
There is a small bug in your code here:
`const chunk = file.slice(chunkSize * 1, Math.max(chunkSize * (i + 1), file.size))`
It should be `const chunk = file.slice(chunkSize * i, Math.min(chunkSize * (i + 1), file.size))`

With this modification + increasing the chunkSize to 64MB I was able to archive a 400 MB/s throughput with a 1.2GB file, which is nice considering the FileReader's overhead.

Demo:
https://codepen.io/daninet/pen/ZEWYYbd

**Comment by CBulFel** [comment]
I'm very sorry, this is my code bug, thank you very much!
