### ISSUE TITLE
Is there any way to optimize it?

### ISSUE THREAD

**Issue by envdevprod** [Daninet/hash-wasm#50]
Hello, Daninet. I'm currently using this library in a Vue project and I want to calculate the SM3 hash of files in Chrome. However, I've noticed that the calculation speed is not very fast for large video files, especially those over 7GB. Is there any way to optimize it?

**Comment by Daninet** [comment]
The library should archive consistent speeds even with files larger than 7GB. The performance might be affected by disk I/O. SSD / HDD read speeds might be slower than the hashing.

**Comment by IVLIU** [comment]
I used a PDF file of about 110MB for testing. js took about 400ms and wasm about 700ms. Is there a threshold and wasm is faster than js?

**Comment by Daninet** [comment]
According to my measurements the threshold is at a few kilobytes and in the other direction and when it's not warmed up. I mean JS might be faster with 1kb of data when the wasm binary is not optimized yet.
Do you have the chrome dev tools open? That has a large impact on WASM performance.

**Comment by IVLIU** [comment]
> According to my measurements the threshold is at a few kilobytes and in the other direction and when it's not warmed up. I mean JS might be faster with 1kb of data when the wasm binary is not optimized yet. Do you have the chrome dev tools open? That has a large impact on WASM performance.

Yes, I opened it, I need to retest
