### ISSUE TITLE
Feature request: Add `secret` parameter to argon2 implementation

### ISSUE THREAD

**Issue by malobre** [Daninet/hash-wasm#53]
<https://github.com/P-H-C/phc-winner-argon2#library> mentions additional parameters, among them:

> The secret parameter, which is used for [keyed hashing](https://en.wikipedia.org/wiki/Hash-based_message_authentication_code). This allows a secret key to be input at hashing time (from some external location) and be folded into the value of the hash. This means that even if your salts and hashes are compromised, an attacker cannot brute-force to find the password without the key.

**Comment by malobre** [comment]
Nevermind, I missed the `createHMAC` function which satifies my need. Sorry for the noise.

**Comment by Daninet** [comment]
I think it's a valid request. For now, here is a workaround: https://security.stackexchange.com/a/206177

**Comment by Daninet** [comment]
Nice. Please submit a PR and I will have a look. Thank you.
