### ISSUE TITLE
Feature request: Whirlpool

### ISSUE THREAD

**Issue by jens-duttke** [Daninet/hash-wasm#6]
Are there any plans to support additional algorithms, like [Whirlpool](https://en.wikipedia.org/wiki/Whirlpool_(hash_function))?

**Comment by Daninet** [comment]
Yeah. I want to add all well-known hash and key derivation algorithms, but I try to prioritize them by popularity. I'm currently working two key derivation algorithms: scrypt and bcrypt. These are a more popular than Whirlpool, but Whirlpool is also on my list.

Thank you for the feature request. 👍

**Comment by Daninet** [comment]
Whirlpool support has landed in version 4.4.0
