### ISSUE TITLE
any plan to support famous encryption algorithms?

### ISSUE THREAD

**Issue by fyears** [Daninet/hash-wasm#61]
Hi,

I found this project very useful! Thanks!

But currently this project mainly focuses on hash, do you have any plan to extend it to support famous encryption algorithms? Such as nacl, XChaCha20-Poly1305, etc? 

Thanks!

**Comment by Daninet** [comment]
Hi, I prefer supporting only hash functions under the "hash-wasm" name. Maybe I will start a new library for encryption when I have a good enough use case.
