### ISSUE TITLE
Performs poorly in comparison to node:crypto

### ISSUE THREAD

**Issue by ankurparihar** [Daninet/hash-wasm#62]
Hi

Wanted to know if this library is meant to be used as a fast replacement for node:crypto. I tried running this on ~20k files. Here are results and code snippet

```js
const crypto = require("node:crypto");
const { sha256 } = require("hash-wasm");

async function getFileHash(filePath) {
  try {
    const content = await fs.readFile(filePath, { encoding: "utf-8" });
    // hash-wasm
    const hash = await sha256(content);
    return hash;
    // node:crypto
    // return crypto.createHash("sha256").update(content).digest("hex");
  } catch (error) {
    console.error("Failed to create hash for file", filePath, error);
  }
}
```

|  | node:crypto | hash-wasm |
|-|-------------|-------------|
| Test 1 | 21911ms | 12935ms |
| Test 2 | 21830ms | 12304ms |
| Test 3 | 21526ms | 12973ms |

Thanks

**Comment by Daninet** [comment]
No, it's not meant to be a replacement of node crypto. Node could utilize specialized CPU instructions to archive better performance. Hash-wasm is optimized for portability and easy use.

**Comment by ankurparihar** [comment]
Understood, thanks!
