### ISSUE TITLE
Feature Request: XXHash3

### ISSUE THREAD

**Issue by intrnl** [Daninet/hash-wasm#8]
Now that XXHash3 values are stable in 0.8.0, are there any plans for it?

**Comment by Daninet** [comment]
Thank you for the feature request. 👍

I'm planning to add new algorithms, but I try to prioritize them by popularity.
XXHash3 relies on SIMD instructions, which are not available in browsers yet. So at this moment I don't expect any performance improvements from it compared to XXHash64. But sure, once the browsers start enabling SIMD instructions I will consider supporting this algorithm as well.

https://www.chromestatus.com/feature/6533147810332672

**Comment by Daninet** [comment]
XXHash3 has landed in v4.8.0.
