### ISSUE TITLE
Distributing the minimal bundles

### ISSUE THREAD

**Issue by nivekuil** [Daninet/hash-wasm#9]
Hi, I'm using this library from clojurescript with shadow-cljs, and to get proper code minification I believe I need to require the individual algorithms from their own separate files. It looks like you have a script `rollup-min.config.js` to build this stuff but the `dist/` only seems to include the big `index.*.js` files. Is it possible for the small files to be distributed too, or some explicit way to have yarn install the rollup-min config instead? I'm not very familiar with the JS tooling here so thanks for the help.

**Comment by Daninet** [comment]
Yeah, currently I only bundle 2 modules: the UMD version and the ESM version. Normally, when you import an algorithm with Webpack, it uses the ESM version of the package and it will automatically remove the unused algorithms from the production bundle. The process is called "tree-shaking". I'm not sure if there is a similar feature in the closure compiler.

But anyway, thank you for highlighting this problem. I will try to come up with a solution in the next version.

**Comment by Daninet** [comment]
If you need a quick solution, you can generate your own build with the following commands:

`npm install`
`npm run build`
`npx rollup --config rollup-min.config.js`

**Comment by Daninet** [comment]
Minified bundles have landed in version 4.4.0

**Comment by nivekuil** [comment]
Thanks, looks like it's now 27.96kb uncompressed, down from 150+.

By the way, I notice that the license header remains unminified -- not sure if that is intended.
